apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring  # Change to your preferred namespace
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: prom/node-exporter:latest
          ports:
            - containerPort: 9100
              name: metrics
          volumeMounts:
            - mountPath: /proc
              name: proc
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        