apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring  # Change to your preferred namespace
  labels:
    app: node-exporter
spec:
  ports:
    - port: 9100
      targetPort: 9100
      protocol: TCP
  selector:
    app: node-exporter