apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: Prometheous-pvc
  namespace: monitoring  # Change to your preferred namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi