apiVersion: v1
kind: PersistentVolume
metadata:
  name: Identity-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/Identity-pv  # Change this path as needed for your environment