apiVersion: v1
kind: PersistentVolume
metadata:
  name: Products-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/Products-pv  # Change this path as needed for your environment