---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: products-pvc
  namespace: Backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 
  storageClassName: gp2