---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: ecommerce
  labels:
    app: rabbitmq-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-app
  template:
    metadata:
      labels:
        app: rabbitmq-app
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          ports:
            - containerPort: 5672   # AMQP port
            - containerPort: 15672   # Management UI port
          envFrom:
            - configMapRef:
                name: rabbitmq-config
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: mongo-storage
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc  # Reference to a PVC for persistent storage