apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: ecommerce  # Specify your namespace
type: Opaque
data:
  username: eW91cm5hbWU=   # Base64 encoded username (e.g., "your-username")
  password: cGFzc3dvcmQ=   # Base64 encoded password (e.g., "your-password")