apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: ecommerce  # Specify your namespace
spec:
  accessModes:
    - ReadWriteOnce  # The volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 5Gi  # Requesting 5Gi of storage
  storageClassName: standard  # Specify the storage class if needed