apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: Backend  
spec:
  serviceName: "rabbitmq"
  replicas: 3  
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management-alpine  # Use the RabbitMQ image with management plugin
          ports:
            - containerPort: 5672  # AMQP port
            - containerPort: 15672  # Management UI port
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret   # Reference to a Secret for credentials
                  key: username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret   # Reference to a Secret for credentials
                  key: password
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq/mnesia

  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi  # Adjust based on your needs
