apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: react-frontend-deployment
  namesapace: Frontend
  annotations: 
    version: "1.0.0"
    kubernetes.io/change-cause: "Updated deployment to version 1.0.0"
  labels:  
    app: frontend-nginx
spec:
  replicas: 3  
  selector:  
    matchLabels:
      app: frontend-nginx  
  strategy:
    type: RollingUpdate  
    rollingUpdate:
      maxSurge: 25%       # Maximum number of new pods that can be created above the desired number of pods
      maxUnavailable: 25%    # Maximum number of pods that can be unavailable during the update
  template:     
    metadata:
      labels:
        app: frontend-nginx
    spec:
      containers:
      - name: nginx
        image: my_private_image.nginx:latest  
        imagePullPolicy: IfNotPresent # here we can use IfNotPresent, Always, Never
        imagePullSecrets:
        - name: my_registry_secret 
        ports:
        - containerPort: 80  
        resources:
            requests:
              memory: "256Mi"  
              cpu: "500m"      
            limits:
              memory: "512Mi"  
              cpu: "100m"   
        # Liveness Probe
        livenessProbe:
          httpGet:
            path: /healthz         # Endpoint to check if the app is alive
            port: 80
          initialDelaySeconds: 10   
          failureThreshold: 3   
          timeoutSeconds: 20    
          periodSeconds: 10          
        # Readiness Probe
        readinessProbe:
          httpGet:
            path: /Ready        # Endpoint to check if the app is ready to serve traffic
            port: 80
          initialDelaySeconds: 10   
          failureThreshold: 3   
          timeoutSeconds: 20    
          periodSeconds: 10          
