---

apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namesapace: ecommerce
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: identity-service