apiVersion: v1
kind: PersistentVolumeClaim  
metadata:
  name: identity-data-pvc  
  namesapace: ecommerce
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: "5Gi"
  storageClassName: my-storage-class