apiVersion: v1
kind: Secret
metadata:
  name: my-registry-secret
  namespace: Backend
type: Opaque
data:
  username: eW91ci11c2VybmFtZQ==  # Base64 encoded "your-username"
  password: eW91ci1wYXNzd29yZA==  # Base64 encoded "your-password"
  email: eW91ckVtYWlsQGV4YW1wbGUuY29t  # Base64 encoded "your-email@example.com"